config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  # root "application#home"
  root "articles#index"
  resources :accounts
  resources :articles do
    resources :comments
    post "/comments/:id/update", as:"update_Comment", to: "comments#update"
  end
  resources :likes, only: [:create, :destroy]
  post "/", as:"create", to: "articles#create"

  get  "home" , as: "home" ,to: "application#home"
end

app/models/account.rb
class Account < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  has_many :comments, through: :articles, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :first_name, presence: true
            { case_sensitive: false }
            # length: { minimum: 3, maximum: 25 }

  validates :last_name, presence: true
           { case_sensitive: false }
            # length: { minimum: 3, maximum: 25 }







  # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # validates :email, presence: true,
  #           uniqueness: { case_sensitive: false },
  #           length: { maximum: 105 },
  #           format: { with: VALID_EMAIL_REGEX }

  after_create :assign_default_role

  def assign_default_role
    self.add_role(:user) if self.roles.blank?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible

  belongs_to :account
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true

  VALID_STATUSES = ['public', 'private', 'archived']

  validates :status, inclusion: { in: VALID_STATUSES }

  def archived?
    status == 'archived'
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  # include Visible
  belongs_to :article

  #
  # VALID_STATUSES = ['public', 'private', 'archived']
  #
  # validates :status, inclusion: { in: VALID_STATUSES }

  # def archived?
  #   status == 'archived'
  # end
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/like.rb
class Like < ApplicationRecord
  validates :account_id, uniqueness: { scope: :article_id}
  belongs_to :account
  belongs_to :article
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :accounts, :join_table => :accounts_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def index
    @accounts = Account.order(created_at: :asc)
  end
  def edit
    @article = Article.find(params[:id])
  end
  def show

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def home
    render "layouts/home"
    end
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number])
    end
  end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_account!
  before_action :acc

  def index
    if current_account.roles.first.name=="admin"
      @articles = Article.all
    else
      @articles = Article.where(status: :public).or(Article.where(account: current_account)).order("created_at DESC")
    end
  end

  def show
    @article = Article.find(params[:id])

  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params_home)
    @article.account_id = current_account.id
    # title name change  to first name
    @article.title=current_account.first_name
    if @article.save
      redirect_to articles_path
    else
      redirect_to root_url
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end


  private
  def article_params
    params.require(:article).permit(:title, :body, :status)
  end
  def article_params_home
    params.permit(:title, :body,:status)
  end
  def acc
    @accounts=Account.all
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    # redirect_to articles_path(@article)
    redirect_back( fallback_location: articles_path(@article))
    @account=current_account
    @comment.account_id= @account.id
    @comment.commenter= @account.first_name
    @comment.save
  end


  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), status: 303
  end

  def edit
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])

  end

  def update
    # comment_params
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])

    if params[:comment][:commenter].present?
     @comment.update!(commenter:params[:comment][:commenter])
    end
    if params[:comment][:body].present?
      @comment.update(body:params[:comment][:body])
    end
    redirect_to article_path(@article), status: 303
  end

  private
  def comment_params
    params.require(:comment).permit( :body)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def  create
    @like = current_account.likes.new(like_params)

    if !@like.save
      flash[:notice] = @like.errors.full_messages.to_sentence
    end
    redirect_to @like
  end
  def  destroy
    @like = current_account.likes.find(params[:id])
    @article = @like
    @like.destroy
    redirect_to @like
  end
  private
  def like_params
    params.require(:like).permit(:article_id)
  end
end

app/controllers/turbo_devise_controller.rb
# app/controllers/turbo_devise_controller.rb

class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/accounts/_rightbar.erb
<% @accounts.each do |account| %>
  <%= account.email %>
  <%= account.roles.pluck(:name) %>
  <%#= link_to 'Edit roles',edit_account_path(account) %>

  <br>
<% end %>

app/views/accounts/edit.html.erb
<%= form_with model: @account do |form| %>
<%#= form.collection_check_boxes :role_ids, Role.all, :id, :name %>

  <%#= form.button :submit %>
<% end %>

app/views/accounts/show.html.erb
<%= stylesheet_link_tag "style", "data-turbo-track": "reload" %>

<%= stylesheet_link_tag "change", "data-turbo-track": "reload" %>




<div class="container" >

  <section class="left">
    <!--    <div class="left-feed-bar">-->
    <div class="feed-logo-bar">
      <img src="<%=image_path("4parts.png") %>" alt="" class="feed-logo" />
      <p class="feed">Feed</p>
    </div>
    <!--    </div>-->
    <!--    <div class="logo-button">-->
    <div class="profile-logo-bar">
      <img src="<%=image_path("person.png") %>" alt="" class="profile-logo" />
      <p class="profile">Profile</p>
    </div>

    <div class="manage-logo-bar">
      <img src="<%=image_path("manage.png") %>" alt="" class="manage-logo" />
      <p class="manage">Manage Users</p>
    </div>


    <div class="logout-logo-bar">
      <img src="<%=image_path(">.png") %>" alt="" class="logout-logo" />
      <p class="logout"><%=button_to "logout", destroy_account_session_url ,method: :delete %></p>
    </div>

  </section>




  <section class="middle">

    <nav class="icon-maze">
      <a href="http://127.0.0.1:3000/"><img src="<%=image_path("Frame 8.png") %>" alt="" class="search-bar-logo" /></a>
      <div class="search-bar">
        <img src="<%=image_path("bi_search.png") %>" alt="" class="search-bar-icon" />

      </div>
    </nav>


    <div class="sub-container">


        <div class="post">

          <div class="title-container">
            <p class="title">



          <div class="form-comment">

            <div class="comment-form">


                <p class="comment-form-input-new">

                </p>

            </div>
          </div>

          <div class="comment-section">
            <p class="intro">comments</p>
            <%#comment=article.comments.first%>
            <%#comment=Comment.where(article_id:article.id)%>

            <div class="comment-box">


    </div>

  </section>
</div>

  <section class="right">


    <div class="Name-Photo-bar">
      <p class="Name">
        <%#= current_account.first_name %>
        <%#= current_account.last_name %>
      </p>

      <img src="<%=image_path("pick.png") %>" alt="" class="Name-Photo" />
    </div>

<!--    <div class="user-details">-->
      <%# if current_account.roles.first.name=="admin" %>
<!--        <p class="user-list">Users List</p><br>-->
        <%#@accounts.each do |acc| %>
          <%# unless acc.articles.blank? %>
<!--            <p class="first-last-name"><%#= image_tag "m1.png" %>    <%#=acc.first_name %>  <%#=acc.last_name %> </p>-->
          <%#end %>
        <%# end %>
      <%# end %>
<!--    </div>-->
  </section>




</div>

app/views/articles/index.html.erb
<%= stylesheet_link_tag "style", "data-turbo-track": "reload" %>

<%= stylesheet_link_tag "change", "data-turbo-track": "reload" %>




<div class="container-flute" >
<div class="row">
  <div class="col-2">
    <div class="LEFT-BOOT">
      <div class="d-flex my-5">

        <a href="http://127.0.0.1:3000/"><%= image_tag ("Frame 8.png") %></a>

      </div>
      <div class="d-flex my-5" >

        <a href="http://127.0.0.1:3000/", class="feed-boot" ><%= image_tag ("4parts.png")%>
          <span >Feed</span></a>

      </div>

      <div class="d-flex my-5">

        <a class="feed-boot"><%= image_tag ("person.png")%>
          <span >Profile</span></a>
<!--        <img src="<%#=image_path("person.png") %>" alt=""  />-->
<!--        <p >Profile</p>-->
      </div>

      <div class="d-flex my-5">

        <a href="http://127.0.0.1:3000/accounts/show", class="feed-boot"><%= image_tag ("manage.png")%>
          <span>Manage Users</span></a>

<!--        <img src="<%#=image_path("manage.png") %>" alt=""  />-->
<!--        <a href="http://127.0.0.1:3000/accounts/show" >-->
<!--          <p >Manage Users</p></a>-->
      </div>


      <div class="d-flex my-5">
        <%= image_tag ">.png", class:"logout-boot" %>
        <p class="feed-boot-strap"><%=link_to "logout", "/accounts/sign_out" ,method: :delete %></p>


<!--        <img src="<%#=image_path(">.png") %>" alt="" />-->
<!--        <p><%#=link_to "logout", destroy_account_session_url ,method: :delete %></p>-->


      </div>

    </div>
  </div>

  <div class="col-8">
    <section>
        <div >
          <%= image_tag "bi_search.png", class:"search-icon" %>
          <input type="text" class="form-control form-control-lg" style="width: 90%;"  name="" id="search-box"  placeholder="Search here for something....."/>
        </div>



      <div class="sub-container">
        <%= render "form", article: @article %>
        <% @articles.order(created_at: :desc).each do |article| %>


          <div class="post">

            <div class="title-container">
              <p class="title">
                <img src="<%=image_path("m1.png") %>" alt="" class="" />
                <a href="http://127.0.0.1:3000/articles/<%=article.id%>"><%=article.title %></a>

              </p>
              <div class="dropdown">
                <button class="btn btn-secondary link-dark" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  ...
                </button>
                <ul class="dropdown-menu dropdown-menu-end">
                  <li><a href="http://localhost:3000/articles/<%=article.id%>/edit" class="edit-post">edit</a></li>

                  <li><%=link_to "delete", article_url(article.id), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  }, class: "edit-post"%></li>
                </ul>
              </div>

            </div>
            <%require 'date' %>

            <p class="date">

              <%= time_ago_in_words(article.created_at) %>.<%= article.status %>

            </p>
            <div class="post-content">
              <p><%=article.body %></p>
            </div>

            <div class="post-features">
              <div class="like">

                <p>like</p>
                <p><%=article.likes.length %></p>
                <% like = current_account.likes.find_by(article: article) %>
                <% if like.nil? %>
                  <form action="/likes" method="post">
                    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                    <input type="hidden" name="like[article_id]" value="<%= article.id %>">
                    <input type="submit" value="like">
                  </form>
                <% else %>
                  <form action="<% like_path(like) %>" method="post">
                    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                    <input type="hidden" name="like[article_id]" value="<%= article.id %>">
                    <input type="hidden" name="like[article_id]"  value="<%= article.id %>">
                    <input type="submit" value="like">
                  </form>
                <% end %>
              </div>
              <div class="comment">
                <!--            <p><%#=article.comments.length%></p>-->
                <p><%=Comment.where(article_id:article.id).count %></p>

                <p>Comments</p>
              </div>
            </div>
            <div class="post-features-icons">

              <img src="<%=image_path("Frame 20.png") %>"alt="">


            </div>


            <div class="form-comment">

              <div class="comment-form">
                <%= form_with model: [ article, article.comments.build ] do |form| %>

                  <p class="comment-form-input-new">
                    <%= form.text_field :body ,placeholder:"Write a comment..."%>
                  </p>
                  <p class="comment-btn-new">
                    <%= button_tag( class: "button", type: "submit") do %>
                      <%= image_tag "teli3.png" %>
                    <% end %>

                  </p>
                <% end %>

              </div>
            </div>

            <div class="comment-section">
              <p class="intro">comments</p>
              <%comment=article.comments.first%>
              <%comment=Comment.where(article_id:article.id)%>

              <div class="comment-box">


                <!--                <p class="comment-content"><%#=comment.body%></p>-->
                <p class="comment-content">
                  <img src="<%=image_path("m1.png") %>" alt="" class="account-name" />
                  <%=comment.present? ?  comment.last.commenter: '' %></p>
                <%=comment.present? ?  comment.last.body : '' %></p>
                <p class="comment-like"></p>
                <!--                <img src="<%#=image_path("DIL.png") %>"alt="">-->

              </div>
            </div>
          </div>
        <% end %>
      </div>
    </section>
  </div>

  <div class="col-2">
    <section class="right">
      <div class="Name-Photo-bar">
        <p class="Name">
          <%= current_account.first_name %>
          <%= current_account.last_name %>
        </p>

        <img src="<%=image_path("pick.png") %>" alt="" class="Name-Photo" />
      </div>

      <div class="user-details">
        <% if current_account.roles.first.name=="admin" %>
          <p class="user-list">Users List</p><br>
          <%@accounts.each do |acc| %>
            <% unless acc.articles.blank? %>
              <p class="first-last-name"><%= image_tag "m1.png" %>    <%=acc.first_name %>  <%=acc.last_name %> </p>
            <%end %>
          <% end %>
        <% end %>
      </div>
    </section>
  </div>
</div>
</div>

<!--..........................<<<<<<<<>>>>>>>>>>>>>>>>>>>>...............-->


<!--  <section class="left">-->
<!--    <div class="left-feed-bar">-->
<!--    <div class="feed-logo-bar">-->
<!--      <a href="http://127.0.0.1:3000/"> <img src="<%#=image_path("4parts.png") %>" alt="" class="feed-logo" /><p class="feed">Feed</p></a>-->
<!--    </div>-->
<!--    </div>-->
<!--    <div class="logo-button">-->
<!--      <div class="profile-logo-bar">-->
<!--        <img src="<%#=image_path("person.png") %>" alt="" class="profile-logo" />-->
<!--        <p class="profile">Profile</p>-->
<!--      </div>-->

<!--      <div class="manage-logo-bar">-->
<!--        <img src="<%#=image_path("manage.png") %>" alt="" class="manage-logo" />-->
<!--        <a href="http://127.0.0.1:3000/accounts/show" ><p class="manage">Manage Users</p></a>-->
<!--      </div>-->


<!--    <div class="logout-logo-bar">-->
<!--    <img src="<%#=image_path(">.png") %>" alt="" class="logout-logo" />-->
<!--    <p class="logout"><%#=button_to "logout", destroy_account_session_url ,method: :delete %></p>-->
<!--   </div>-->

<!--  </section>-->




<!--  <section class="middle">-->

<!--  <nav class="icon-maze">-->
<!--    <a href="http://127.0.0.1:3000/"><img src="<%#=image_path("Frame 8.png") %>" alt="" class="search-bar-logo" /></a>-->
<!--    <div class="search-bar">-->
<!--      <img src="<%#=image_path("bi_search.png") %>" alt="" class="search-bar-icon" />-->
<!--      <input type="text" name="" id="" class="search-bar-input" placeholder="Search here for something....."/>-->
<!--    </div>-->
<!--  </nav>-->


<!--  <div class="sub-container">-->
    <%#= render "form", article: @article %>
    <%# @articles.order(created_at: :desc).each do |article| %>


<!--      <div class="post">-->

<!--        <div class="title-container">-->
<!--          <p class="title">-->
<!--            <img src="<%#=image_path("m1.png") %>" alt="" class="" />-->
<!--            <a href="http://127.0.0.1:3000/articles/<%#=article.id%>"><%#=article.title %></a>-->

<!--          </p>-->
<!--          <div class="dropdown">-->
<!--            <button class="btn btn-secondary link-dark" type="button" data-bs-toggle="dropdown" aria-expanded="false">-->
<!--               ...-->
<!--            </button>-->
<!--            <ul class="dropdown-menu dropdown-menu-end">-->
<!--              <li><a href="http://localhost:3000/articles/<%#=article.id%>/edit" class="edit-post">edit</a></li>-->

<!--              <li><%#=link_to "delete", article_url(article.id), data: {-->
<!--                turbo_method: :delete,-->
<!--                turbo_confirm: "Are you sure?"-->
<!--              }, class: "edit-post"%></li>-->
<!--            </ul>-->
<!--          </div>-->

<!--        </div>-->
        <%#require 'date' %>

<!--        <p class="date">-->
          <%#=article.created_at.to_da?te%>
<!--          <%#= time_ago_in_words(article.created_at) %>.<%#= article.status %>-->

<!--        </p>-->
<!--        <div class="post-content">-->
<!--          <p><%#=article.body %></p>-->
<!--        </div>-->

<!--        <div class="post-features">-->
<!--          <div class="like">-->

<!--            <p>like</p>-->
<!--            <p><%#=article.likes.length %></p>-->

            <%# like = current_account.likes.find_by(article: article) %>
            <%# if like.nil? %>
<!--              <form action="/likes" method="post">-->
<!--                <input type="hidden" name="authenticity_token" value="<%#= form_authenticity_token %>">-->
<!--                <input type="hidden" name="like[article_id]" value="<%#= article.id %>">-->
<!--                <input type="submit" value="like">-->
<!--              </form>-->
            <%# else %>
<!--              <form action="<%# like_path(like) %>" method="post">-->
<!--                <input type="hidden" name="authenticity_token" value="<%#= form_authenticity_token %>">-->
<!--                <input type="hidden" name="like[article_id]" value="<%#= article.id %>">-->
<!--                <input type="hidden" name="like[article_id]"  value="<%#= article.id %>">-->
<!--                <input type="submit" value="like">-->
<!--              </form>-->
            <%# end %>
<!--          </div>-->
<!--          <div class="comment">-->
<!--            <p><%#=article.comments.length%></p>-->
<!--            <p><%#=Comment.where(article_id:article.id).count %></p>-->

<!--            <p>Comments</p>-->
<!--          </div>-->
<!--        </div>-->
<!--        <div class="post-features-icons">-->

<!--          <img src="<%#=image_path("Frame 20.png") %>"alt="">-->


<!--        </div>-->


<!--        <div class="form-comment">-->

<!--          <div class="comment-form">-->
            <%#= form_with model: [ article, article.comments.build ] do |form| %>

<!--              <p class="comment-form-input-new">-->
                <%#= form.text_field :body ,placeholder:"Write a comment..."%>
<!--              </p>-->
<!--              <p class="comment-btn-new">-->
                <%#= form.submit ""%>
                <%#= button_tag( class: "button", type: "submit") do %>
                  <%#= image_tag "teli3.png" %>
                    <%# end %>

<!--              </p>-->
            <%# end %>

<!--          </div>-->
<!--        </div>-->

<!--        <div class="comment-section">-->
<!--          <p class="intro">comments</p>-->
            <%#comment=article.comments.first%>
          <%#comment=Comment.where(article_id:article.id)%>

<!--              <div class="comment-box">-->


<!--                <p class="comment-content"><%#=comment.body%></p>-->
<!--                <p class="comment-content">-->
<!--                  <img src="<%#=image_path("m1.png") %>" alt="" class="account-name" />-->
<!--                  <%#=comment.present? ?  comment.last.commenter: '' %></p>-->
<!--                <%#=comment.present? ?  comment.last.body : '' %></p>-->
<!--                <p class="comment-like"></p>-->
<!--                <img src="<%#=image_path("DIL.png") %>"alt="">-->

<!--              </div>-->
<!--        </div>-->
<!--      </div>-->
    <%# end %>
<!--  </div>-->

<!--</section>-->


<!--  <section class="right">-->


<!--    <div class="Name-Photo-bar">-->
<!--      <p class="Name">-->
      <%#= current_account.first_name %>
        <%#= current_account.last_name %>
<!--      </p>-->

<!--      <img src="<%#=image_path("pick.png") %>" alt="" class="Name-Photo" />-->
<!--    </div>-->

<!--    <div class="user-details">-->
      <%# if current_account.roles.first.name=="admin" %>
<!--        <p class="user-list">Users List</p><br>-->
        <%#@accounts.each do |acc| %>
        <%# unless acc.articles.blank? %>
<!--          <p class="first-last-name"><%#= image_tag "m1.png" %>    <%#=acc.first_name %>  <%#=acc.last_name %> </p>-->
      <%#end %>
    <%# end %>
      <%# end %>
<!--    </div>-->
<!--  </section>-->


</div>

app/views/articles/show.html.erb
<%= stylesheet_link_tag "show.css", "data-turbo-track": "reload" %>

<%= stylesheet_link_tag "change", "data-turbo-track": "reload" %>

<div class="container">

  <section class="left">
    <div class="feed-logo-bar">
      <img src="<%=image_path("4parts.png") %>" alt="" class="feed-logo" />
      <p class="feed">Feed</p>
    </div>
    <div class="logo-button">
      <div class="profile-logo-bar">
        <img src="<%=image_path("person.png") %>" alt="" class="profile-logo" />
        <p class="profile">Profile</p>
      </div>

    </div>

    <p class="logout-logo-bar"><img src="<%=image_path(">.png") %>" alt="" class="logout-logo" />
    <p class="logout"><%=button_to "logout", destroy_account_session_url ,method: :delete %></p>

  </section>

  <section class="middle">

  <nav class="icon-maze">
    <a href="http://127.0.0.1:3000/"><img src="<%=image_path("Frame 8.png") %>" alt="" class="search-bar-logo" /></a>
    <div class="search-bar">
      <img src="<%=image_path("bi_search.png") %>" alt="" class="search-bar-icon" />
      <input type="text" name="" id="" class="search-bar-input" placeholder="Search here for something....."/>
    </div>
  </nav>

  <div class="sub-container">



    <div class="post">

      <div class="title-container">
        <p class="title">
          <img src="<%=image_path("m1.png") %>" alt="" class="" /><%=@article.title %></p>
        <div class="dropdown">
          <button class="btn btn-secondary" type="button"data-bs-toggle="dropdown" aria-expanded="false">
            ...
          </button>
          <ul class="dropdown-menu">
            <li><a href="http://localhost:3000/articles/<%=@article.id%>/edit" class="edit-post">edit</a></li>
            <li><%=link_to "delete" , @article_urL, data: {
              turbo_method: :delete,
              turbo_confirm: "Are you sure?"
            },class: "edit-post" %></li>
          </ul>
        </div>
      </div>
      <p class="date">
        <%#=@article.created_at.to_date%>
        <%= time_ago_in_words(@article.created_at) %>.<%= @article.status %>
      </p>
      <div class="post-content">
        <p><%=@article.body %></p>
      </div>

      <div class="post-features">
        <div class="like">
          <p>Likes</p>
          <p><%=@article.likes.length %></p>

          <% like = current_account.likes.find_by(article: @article) %>
          <% if like.nil? %>
          <form action="/likes" method="post">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input type="hidden" name="like[article_id]" value="<%= @article.id %>">
            <input type="submit" value="like">
          </form>
          <% else %>
          <form action="<% like_path(like) %>" method="post">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input type="hidden" name="like[article_id]" value="<%= @article.id %>">
            <input type="hidden" name="like[article_id]"  value="<%= @article.id %>">
            <input type="submit" value="like" class="">
          </form>
          <% end %>

        </div>
        <div class="comment">
          <p><%=@article.comments.length%></p>
          <p>Comments</p>
        </div>
      </div>
      <div class="post-features-icons">
        <img src="<%=image_path("Frame 20.png") %>"alt="">

      </div>


      <div class="comment-form">

          <div class="comment-form" ></div>
          <%= render 'comments/form' ,article:@article, comment:@article.comments.build %>


      </div>


      <div class="comment-section">
        <p class="intro">comments</p>
        <div class="comment-box-new">
          <%= render @article.comments.order(created_at: :desc) %>
        </div>
        </div>

    </div>

  </div>

  </section>




  <section class="right">
    <div class="Name-Photo-bar">
      <p class="Name">
        <%= current_account.first_name %>
        <%= current_account.last_name %>
      </p>

      <img src="<%=image_path("pick.png") %>" alt="" class="Name-Photo" />
    </div>
  </section>

</div>

app/views/layouts/home.html.erb
<%= stylesheet_link_tag "login", "data-turbo-track": "reload" %>



<body>
<header class="header">

  <div class="logo">

    <img src="<%=image_path("m.png") %>" alt="" class="logo-m">
    <img src="<%=image_path("fw.png") %>" alt="" class="logo-maze">
  </div>
  <div class="line"></div>
  <div class="text">
    <h1 style="color:white;">Social media shared today, tomorrow or by location</h1>
    <h3 style="color:white;">Discover with Maze</h3>
  </div>

  <div class="user">
    <button class="Create" ><%=link_to "create account" ,new_account_registration_url%></button>

    <h4 class="or">or</h4>

    <button class="login"><%=link_to"login" ,new_account_session_url %></button>
  </div>

</header>
</body>